/**
 * Bureau of Indian Standards (BIS) Master Knowledge Base
 * 41 curated Indian Standards across 9 categories with compliance metadata,
 * mandatory QCO status, testing cross-references, and sample tender clauses.
 */

export const IS_CATEGORIES = [
  'All Categories',
  'Construction Materials - Cement',
  'Construction Materials - Concrete',
  'Construction Materials - Masonry',
  'Construction Materials - Paving',
  'Electrical - Appliances',
  'Electrical - Cables',
  'Electrical - Enclosures',
  'Electrical - Motors',
  'Electrical - Safety',
  'Electrical - Switchgear',
  'Electrical - Wiring',
  'Furniture & Fixtures',
  'IT & Electronics',
  'IT & Information Security',
  'Metals & Castings',
  'Safety & PPE',
  'Structural Steel',
  'Structural Steel - Pipes',
  'Water & Environment',
  'Water & Environment - Pipes',
  'Water & Environment - Testing'
];

export const STANDARDS_DATABASE = [
  // ── Cement ─────────────────────────────────────────────────────────────────
  {
    id: 'STD001',
    code: 'IS 269:2015',
    cleanCode: 'IS 269',
    title: 'Ordinary Portland Cement, 33 Grade — Specification',
    category: 'Construction Materials - Cement',
    year: 2015,
    mandatory: true,
    qcoStatus: 'Mandatory under Cement Quality Control Order (QCO)',
    scope: 'General purpose Ordinary Portland Cement for non-structural and low-grade concrete applications, plastering, and masonry mortar.',
    keywords: ['cement', 'opc', '33 grade', 'plastering', 'masonry mortar', 'portland cement', 'low grade concrete'],
    testingStandards: ['IS 4031', 'IS 4032'],
    clauseSnippet: 'Ordinary Portland Cement (33 Grade) conforming to IS 269:2015 with valid BIS Standard Mark (ISI mark).'
  },
  {
    id: 'STD002',
    code: 'IS 8112:2013',
    cleanCode: 'IS 8112',
    title: 'Ordinary Portland Cement, 43 Grade — Specification',
    category: 'Construction Materials - Cement',
    year: 2013,
    mandatory: true,
    qcoStatus: 'Mandatory under Cement Quality Control Order (QCO)',
    scope: 'OPC for general RCC structural work, residential buildings, bridges, culverts, and commercial civil infrastructure.',
    keywords: ['cement', 'opc', '43 grade', 'rcc', 'reinforced concrete', 'structural work', 'portland cement', 'columns', 'beams', 'slabs'],
    testingStandards: ['IS 4031', 'IS 4032'],
    clauseSnippet: 'Ordinary Portland Cement (43 Grade) conforming to IS 8112:2013 with mandatory BIS certification.'
  },
  {
    id: 'STD003',
    code: 'IS 12269:2013',
    cleanCode: 'IS 12269',
    title: 'Ordinary Portland Cement, 53 Grade — Specification',
    category: 'Construction Materials - Cement',
    year: 2013,
    mandatory: true,
    qcoStatus: 'Mandatory under Cement Quality Control Order (QCO)',
    scope: 'High-strength OPC for heavy structural, pre-stressed concrete, high-rise buildings, runways, and precast concrete work.',
    keywords: ['cement', 'opc', '53 grade', 'high strength cement', 'prestressed concrete', 'precast', 'high rise', 'heavy civil'],
    testingStandards: ['IS 4031', 'IS 4032'],
    clauseSnippet: 'Ordinary Portland Cement (53 Grade) conforming to IS 12269:2013 with BIS Certification Mark.'
  },
  {
    id: 'STD004',
    code: 'IS 1489 (Part 1):2015',
    cleanCode: 'IS 1489',
    title: 'Portland Pozzolana Cement — Fly Ash Based — Specification',
    category: 'Construction Materials - Cement',
    year: 2015,
    mandatory: true,
    qcoStatus: 'Mandatory under Cement Quality Control Order (QCO)',
    scope: 'PPC using pozzolanic fly ash, common in mass concreting, marine works, hydraulic structures, and plastering with improved sulphate resistance.',
    keywords: ['ppc', 'fly ash', 'pozzolana', 'portland pozzolana cement', 'mass concrete', 'marine concrete', 'dam construction'],
    testingStandards: ['IS 4031', 'IS 4032'],
    clauseSnippet: 'Portland Pozzolana Cement (Fly Ash based) conforming to IS 1489 (Part 1):2015 bearing BIS standard certification.'
  },
  {
    id: 'STD005',
    code: 'IS 455:1989',
    cleanCode: 'IS 455',
    title: 'Portland Slag Cement — Specification',
    category: 'Construction Materials - Cement',
    year: 1989,
    mandatory: true,
    qcoStatus: 'Mandatory under Cement Quality Control Order (QCO)',
    scope: 'Slag-blended cement for marine construction, foundations in aggressive saline or sulphate soil environments, and mass concrete works.',
    keywords: ['slag cement', 'portland slag', 'psc', 'marine works', 'saline soil', 'blast furnace slag', 'sulphate resistant'],
    testingStandards: ['IS 4031', 'IS 4032'],
    clauseSnippet: 'Portland Slag Cement conforming to IS 455:1989 with mandatory BIS certification.'
  },

  // ── Concrete & Aggregates ──────────────────────────────────────────────────
  {
    id: 'STD006',
    code: 'IS 456:2000',
    cleanCode: 'IS 456',
    title: 'Plain and Reinforced Concrete — Code of Practice',
    category: 'Construction Materials - Concrete',
    year: 2000,
    mandatory: false,
    qcoStatus: 'National Code of Practice (Mandatory by CPWD & State PWD specs)',
    scope: 'General structural design and construction practice for plain and reinforced concrete, covering mix design, durability, curing, and reinforcement detailing.',
    keywords: ['concrete', 'rcc', 'plain concrete', 'reinforcement', 'mix design', 'code of practice', 'curing', 'structural design', 'beams', 'columns'],
    testingStandards: ['IS 516', 'IS 1199'],
    clauseSnippet: 'Concrete works and structural design shall strictly adhere to the guidelines of IS 456:2000.'
  },
  {
    id: 'STD007',
    code: 'IS 383:2016',
    cleanCode: 'IS 383',
    title: 'Coarse and Fine Aggregate for Concrete — Specification',
    category: 'Construction Materials - Concrete',
    year: 2016,
    mandatory: false,
    qcoStatus: 'Standard Specification for Civil Works',
    scope: 'Quality parameters, grading limits, deleterious material limits, and particle shape requirements for natural and manufactured coarse and fine aggregates in concrete.',
    keywords: ['aggregate', 'coarse aggregate', 'fine aggregate', 'sand', 'm-sand', 'gravel', 'crushed stone', 'grading zone', 'concrete mix'],
    testingStandards: ['IS 2386'],
    clauseSnippet: 'Coarse and fine aggregates shall strictly comply with the grading and quality requirements of IS 383:2016.'
  },
  {
    id: 'STD008',
    code: 'IS 3812 (Part 1):2013',
    cleanCode: 'IS 3812',
    title: 'Pulverized Fuel Ash — Specification (Concrete/Mortar use)',
    category: 'Construction Materials - Concrete',
    year: 2013,
    mandatory: false,
    qcoStatus: 'Standard Specification',
    scope: 'Use of pulverized fuel ash (fly ash) as pozzolana and mineral admixture in design of cement concrete and cement mortar.',
    keywords: ['fly ash', 'pulverized fuel ash', 'mineral admixture', 'pozzolanic', 'concrete additive'],
    testingStandards: ['IS 1727'],
    clauseSnippet: 'Fly ash used as mineral admixture shall conform to IS 3812 (Part 1):2013 Grade I.'
  },

  // ── Masonry ────────────────────────────────────────────────────────────────
  {
    id: 'STD009',
    code: 'IS 2185 (Part 1):2005',
    cleanCode: 'IS 2185',
    title: 'Concrete Masonry Units — Hollow/Solid Concrete Blocks',
    category: 'Construction Materials - Masonry',
    year: 2005,
    mandatory: true,
    qcoStatus: 'Mandatory under Precast Concrete QCO',
    scope: 'Specifications for precast solid and hollow concrete blocks used for load-bearing and non-load-bearing masonry wall construction.',
    keywords: ['concrete blocks', 'hollow blocks', 'solid blocks', 'masonry units', 'precast blocks', 'partition wall', 'blockwork'],
    testingStandards: ['IS 2185'],
    clauseSnippet: 'Concrete masonry blocks shall conform to IS 2185 (Part 1):2005 with BIS license.'
  },
  {
    id: 'STD010',
    code: 'IS 1077:1992',
    cleanCode: 'IS 1077',
    title: 'Common Burnt Clay Building Bricks — Specification',
    category: 'Construction Materials - Masonry',
    year: 1992,
    mandatory: false,
    qcoStatus: 'Standard Specification for Building Works',
    scope: 'Physical requirements, dimensions, compressive strength classes, and water absorption limits for common burnt clay building bricks.',
    keywords: ['clay bricks', 'burnt clay', 'red bricks', 'building bricks', 'brickwork', 'masonry bricks', 'brick masonry'],
    testingStandards: ['IS 3495'],
    clauseSnippet: 'Common burnt clay bricks shall conform to IS 1077:1992 class designation 7.5 or above.'
  },

  // ── Paving ─────────────────────────────────────────────────────────────────
  {
    id: 'STD011',
    code: 'IS 15658:2006',
    cleanCode: 'IS 15658',
    title: 'Precast Concrete Blocks for Paving — Specification',
    category: 'Construction Materials - Paving',
    year: 2006,
    mandatory: false,
    qcoStatus: 'Standard Specification for Urban Infra',
    scope: 'Requirements for interlocking precast concrete paver blocks for pedestrian footpaths, parking lots, heavy-duty industrial pavements, and bus terminals.',
    keywords: ['paver blocks', 'interlocking pavers', 'paving blocks', 'footpath pavers', 'parking pavement', 'precast paving'],
    testingStandards: ['IS 15658'],
    clauseSnippet: 'Interlocking paver blocks shall satisfy the compressive strength and abrasion resistance requirements of IS 15658:2006.'
  },

  // ── Structural Steel & Rebar ───────────────────────────────────────────────
  {
    id: 'STD012',
    code: 'IS 1786:2008',
    cleanCode: 'IS 1786',
    title: 'High Strength Deformed Steel Bars/Wires for Concrete Reinforcement',
    category: 'Structural Steel',
    year: 2008,
    mandatory: true,
    qcoStatus: 'Mandatory under Steel and Steel Products Quality Control Order',
    scope: 'High-strength deformed steel bars and wires (TMT rebar, Fe 415, Fe 500, Fe 500D, Fe 550, Fe 600) for reinforcement in RCC structures, bridges, and foundations.',
    keywords: ['tmt bars', 'rebar', 'reinforcement steel', 'fe 500d', 'fe 500', 'fe 550', 'deformed bars', 'steel rods', 'rcc reinforcement', 'high yield strength'],
    testingStandards: ['IS 1608', 'IS 1599'],
    clauseSnippet: 'Thermo-Mechanically Treated (TMT) steel bars grade Fe 500D shall strictly conform to IS 1786:2008 and bear the mandatory BIS Standard Mark (ISI mark).'
  },
  {
    id: 'STD013',
    code: 'IS 2062:2011',
    cleanCode: 'IS 2062',
    title: 'Hot Rolled Medium and High Tensile Structural Steel — Specification',
    category: 'Structural Steel',
    year: 2011,
    mandatory: true,
    qcoStatus: 'Mandatory under Steel Quality Control Order',
    scope: 'Structural steel sections (angles, channels, beams, plates, flats) for welded, riveted, or bolted fabrication of bridges, transmission towers, and industrial sheds.',
    keywords: ['structural steel', 'ms plates', 'steel sections', 'i-beam', 'c-channel', 'steel angles', 'hot rolled steel', 'fabrication steel', 'e250', 'e350'],
    testingStandards: ['IS 1608', 'IS 1757'],
    clauseSnippet: 'Structural steel sections and plates shall conform to IS 2062:2011 Grade E250/E350 with BIS certification.'
  },
  {
    id: 'STD014',
    code: 'IS 800:2007',
    cleanCode: 'IS 800',
    title: 'General Construction in Steel — Code of Practice',
    category: 'Structural Steel',
    year: 2007,
    mandatory: false,
    qcoStatus: 'National Structural Design Code (Limit State Method)',
    scope: 'Design, fabrication, and erection code of practice for structural steelwork in buildings, trusses, and general engineering construction.',
    keywords: ['steel design', 'steel structure', 'truss fabrication', 'limit state design', 'steel fabrication code', 'bolted connections', 'welded steel structure'],
    testingStandards: ['IS 800'],
    clauseSnippet: 'Design, fabrication, and erection of structural steelwork shall comply with IS 800:2007.'
  },
  {
    id: 'STD015',
    code: 'IS 1239 (Part 1):2004',
    cleanCode: 'IS 1239',
    title: 'Steel Tubes, Tubulars and Other Wrought Steel Fittings — Mild Steel Tubes',
    category: 'Structural Steel - Pipes',
    year: 2004,
    mandatory: true,
    qcoStatus: 'Mandatory under Steel Pipes Quality Control Order',
    scope: 'Mild steel tubes (black and galvanized / GI pipes) for water, non-hazardous gas, air, and structural applications like scaffolding and railings.',
    keywords: ['ms pipes', 'gi pipes', 'galvanized iron pipes', 'mild steel tubes', 'tubular scaffolding', 'steel tubing', 'plumbing pipes'],
    testingStandards: ['IS 1239'],
    clauseSnippet: 'Mild steel pipes (GI/Black) shall conform to IS 1239 (Part 1):2004 with mandatory ISI marking.'
  },
  {
    id: 'STD016',
    code: 'IS 3589:2001',
    cleanCode: 'IS 3589',
    title: 'Steel Pipes for Water and Sewage (168.3 to 2540 mm Outside Diameter)',
    category: 'Structural Steel - Pipes',
    year: 2001,
    mandatory: false,
    qcoStatus: 'Standard Specification for Municipal Water Pipelines',
    scope: 'Large-diameter seamless and welded steel pipes for high-capacity municipal water transmission mains and sewage conveyance lines.',
    keywords: ['steel pipes', 'water transmission pipe', 'large diameter pipe', 'sewage steel pipe', 'welded steel pipe', 'water supply pipeline'],
    testingStandards: ['IS 3589'],
    clauseSnippet: 'Large diameter steel water transmission pipes shall conform to IS 3589:2001.'
  },
  {
    id: 'STD017',
    code: 'IS 4923:2017',
    cleanCode: 'IS 4923',
    title: 'Hollow Steel Sections for Structural Use — Specification',
    category: 'Structural Steel',
    year: 2017,
    mandatory: false,
    qcoStatus: 'Standard Specification for Architectural & Industrial Sheds',
    scope: 'Square and rectangular hollow structural steel sections (SHS/RHS) for modern industrial sheds, space frames, sports complexes, and facades.',
    keywords: ['hollow steel sections', 'shs', 'rhs', 'square hollow section', 'rectangular hollow section', 'box sections', 'space frames'],
    testingStandards: ['IS 4923'],
    clauseSnippet: 'Hollow steel sections (SHS/RHS) shall conform to IS 4923:2017 grade YSt 210/310.'
  },

  // ── Metals & Castings ──────────────────────────────────────────────────────
  {
    id: 'STD018',
    code: 'IS 210:2009',
    cleanCode: 'IS 210',
    title: 'Grey Iron Castings — Specification',
    category: 'Metals & Castings',
    year: 2009,
    mandatory: false,
    qcoStatus: 'Standard Specification',
    scope: 'Graded grey cast iron components for manhole covers, pump casings, valves, machine beds, and municipal drainage fittings.',
    keywords: ['grey iron', 'cast iron', 'manhole cover', 'drainage frame', 'pump casing', 'ci casting', 'ci fittings'],
    testingStandards: ['IS 210'],
    clauseSnippet: 'Cast iron manhole covers and frames shall conform to IS 210:2009 Grade FG 200 or higher.'
  },
  {
    id: 'STD019',
    code: 'IS 1030:1998',
    cleanCode: 'IS 1030',
    title: 'Carbon Steel Castings for General Engineering Purposes',
    category: 'Metals & Castings',
    year: 1998,
    mandatory: false,
    qcoStatus: 'Standard Specification',
    scope: 'Carbon steel castings for general engineering components, machinery mounts, and industrial valve bodies subjected to high stress.',
    keywords: ['steel castings', 'carbon steel castings', 'valve body casting', 'engineering castings', 'machine parts'],
    testingStandards: ['IS 1030'],
    clauseSnippet: 'Carbon steel castings shall meet the mechanical and chemical requirements of IS 1030:1998.'
  },

  // ── Electrical ─────────────────────────────────────────────────────────────
  {
    id: 'STD020',
    code: 'IS 732:2019',
    cleanCode: 'IS 732',
    title: 'Code of Practice for Electrical Wiring Installations',
    category: 'Electrical - Wiring',
    year: 2019,
    mandatory: false,
    qcoStatus: 'National Wiring Code (Mandatory in Central CEA Regulations)',
    scope: 'Comprehensive guidelines for safety, design, selection, erection, and testing of electrical wiring installations in residential and commercial buildings.',
    keywords: ['electrical wiring', 'building wiring', 'conduit wiring', 'wiring code', 'internal electrification', 'circuit installation'],
    testingStandards: ['IS 732'],
    clauseSnippet: 'All electrical wiring and installation works shall strictly comply with IS 732:2019 and Central Electricity Authority regulations.'
  },
  {
    id: 'STD021',
    code: 'IS 694:2010',
    cleanCode: 'IS 694',
    title: 'PVC Insulated Cables for Working Voltages up to and Including 1100 V',
    category: 'Electrical - Cables',
    year: 2010,
    mandatory: true,
    qcoStatus: 'Mandatory under Cables Quality Control Order (QCO)',
    scope: 'Single and multicore PVC insulated unsheathed and sheathed copper/aluminium conductor cables for internal building wiring and power distribution up to 1.1 kV.',
    keywords: ['pvc cables', '1100v cables', 'copper wire', 'building wire', 'fr cables', 'frls cables', 'electrical wire', 'house wiring', 'low voltage cable'],
    testingStandards: ['IS 10810', 'IS 8130'],
    clauseSnippet: 'PVC insulated copper cables (FRLS) for 1100V grade shall conform to IS 694:2010 and bear the mandatory BIS certification mark (ISI mark).'
  },
  {
    id: 'STD022',
    code: 'IS 1554 (Part 1):1988',
    cleanCode: 'IS 1554',
    title: 'PVC Insulated (Heavy Duty) Electric Cables for Working Voltages up to 1100 V',
    category: 'Electrical - Cables',
    year: 1988,
    mandatory: true,
    qcoStatus: 'Mandatory under Heavy Duty Cables QCO',
    scope: 'Armoured and unarmoured heavy-duty PVC insulated power and control cables for underground cabling, sub-stations, and industrial feeder lines.',
    keywords: ['heavy duty cable', 'armoured cable', 'power cable', 'underground cable', 'feeder cable', 'pvc power cable', '1100v power cable'],
    testingStandards: ['IS 10810'],
    clauseSnippet: 'Heavy-duty armoured power cables for 1.1 kV grade shall conform to IS 1554 (Part 1):1988 with BIS standard mark.'
  },
  {
    id: 'STD023',
    code: 'IS 8130:2013',
    cleanCode: 'IS 8130',
    title: 'Conductors for Insulated Electric Cables and Flexible Cords',
    category: 'Electrical - Cables',
    year: 2013,
    mandatory: false,
    qcoStatus: 'Component Specification for Electrical Cables',
    scope: 'Standard conductivity, resistance limits, and flexibility classes for annealed copper and aluminium conductors used in insulated power cables.',
    keywords: ['conductors', 'copper conductor', 'aluminium conductor', 'flexible cord', 'cable conductor', 'electrical conductivity'],
    testingStandards: ['IS 8130'],
    clauseSnippet: 'Conductors of supplied electrical cables shall conform to IS 8130:2013 Class 2/Class 5.'
  },
  {
    id: 'STD024',
    code: 'IS 3043:2018',
    cleanCode: 'IS 3043',
    title: 'Code of Practice for Earthing',
    category: 'Electrical - Safety',
    year: 2018,
    mandatory: false,
    qcoStatus: 'National Earthing Code of Practice',
    scope: 'Design, sizing, installation, and maintenance of electrical earthing systems (pipe, plate, chemical gel earthing) for substations, data centers, and buildings.',
    keywords: ['earthing', 'grounding', 'earthing pit', 'plate earthing', 'pipe earthing', 'server room earthing', 'chemical earthing', 'earth electrode'],
    testingStandards: ['IS 3043'],
    clauseSnippet: 'Earthing design, electrode installation, and earth resistance testing shall strictly adhere to IS 3043:2018.'
  },
  {
    id: 'STD025',
    code: 'IS/IEC 60529:2001',
    cleanCode: 'IS/IEC 60529',
    title: 'Degrees of Protection Provided by Enclosures (IP Code)',
    category: 'Electrical - Enclosures',
    year: 2001,
    mandatory: false,
    qcoStatus: 'International Ingress Protection Standard Adopted by BIS',
    scope: 'Classification and testing of enclosures against ingress of solid foreign objects (dust, grit) and water ingress (IP55, IP65, IP66, IP67, IP68).',
    keywords: ['ip code', 'ip65', 'ip66', 'ip67', 'ip55', 'weatherproof enclosure', 'ingress protection', 'dustproof', 'waterproof enclosure', 'junction box'],
    testingStandards: ['IS/IEC 60529'],
    clauseSnippet: 'Enclosures and junction boxes shall provide ingress protection of at least IP65 as certified per IS/IEC 60529:2001.'
  },
  {
    id: 'STD026',
    code: 'IS 900:1992',
    cleanCode: 'IS 900',
    title: 'Code of Practice for Installation and Maintenance of Induction Motors',
    category: 'Electrical - Motors',
    year: 1992,
    mandatory: false,
    qcoStatus: 'Standard Code of Practice for Electrical Plant',
    scope: 'Erection, alignment, foundation design, cabling, and regular maintenance procedures for 3-phase and single-phase AC induction motors.',
    keywords: ['induction motor', 'electric motor', 'motor installation', 'pump motor', 'ac motor', 'motor maintenance'],
    testingStandards: ['IS 900'],
    clauseSnippet: 'Installation and commissioning of electric induction motors shall comply with IS 900:1992.'
  },
  {
    id: 'STD027',
    code: 'IS 13947 (Part 1):1993',
    cleanCode: 'IS 13947',
    title: 'Low-Voltage Switchgear and Controlgear — General Rules',
    category: 'Electrical - Switchgear',
    year: 1993,
    mandatory: true,
    qcoStatus: 'Mandatory under Low Voltage Switchgear QCO',
    scope: 'General rules and safety requirements for low-voltage circuit breakers (MCBs, MCCBs, contactors, isolators) up to 1000V AC or 1500V DC.',
    keywords: ['switchgear', 'mcb', 'mccb', 'circuit breaker', 'distribution board', 'isolator', 'controlgear', 'electrical panel'],
    testingStandards: ['IS 13947'],
    clauseSnippet: 'Low voltage switchgear and circuit breakers shall conform to IS 13947 with mandatory BIS standard mark.'
  },
  {
    id: 'STD028',
    code: 'IS 302 (Part 1):2008',
    cleanCode: 'IS 302',
    title: 'Safety of Household and Similar Electrical Appliances — General Requirements',
    category: 'Electrical - Appliances',
    year: 2008,
    mandatory: true,
    qcoStatus: 'Mandatory under Electrical Appliances Safety QCO',
    scope: 'Baseline electrical and mechanical safety rules for electrical appliances (water heaters, geysers, air conditioners, fans, irons, kitchen appliances).',
    keywords: ['electrical appliances', 'geyser', 'water heater', 'room heater', 'ceiling fan', 'home appliances', 'electrical safety'],
    testingStandards: ['IS 302'],
    clauseSnippet: 'Supplied electrical appliances shall strictly comply with IS 302 (Part 1):2008 with mandatory ISI certification.'
  },

  // ── Water & Environment ────────────────────────────────────────────────────
  {
    id: 'STD029',
    code: 'IS 10500:2012',
    cleanCode: 'IS 10500',
    title: 'Drinking Water — Specification',
    category: 'Water & Environment',
    year: 2012,
    mandatory: false,
    qcoStatus: 'National Drinking Water Benchmark (Jal Jeevan Mission Standard)',
    scope: 'Acceptable limits and permissible limits for chemical, physical, bacteriological, and toxicological parameters of potable drinking water.',
    keywords: ['drinking water', 'potable water', 'water quality', 'jal jeevan mission', 'ro water', 'water supply', 'water purification', 'tds', 'coliform'],
    testingStandards: ['IS 3025'],
    clauseSnippet: 'Treated drinking water supply shall conform to the acceptable and permissible limits of IS 10500:2012.'
  },
  {
    id: 'STD030',
    code: 'IS 4985:2000',
    cleanCode: 'IS 4985',
    title: 'Unplasticized PVC Pipes for Potable Water Supplies — Specification',
    category: 'Water & Environment - Pipes',
    year: 2000,
    mandatory: true,
    qcoStatus: 'Mandatory under PVC Pipes Quality Control Order',
    scope: 'uPVC pressure pipes for cold drinking water conveyance, tubewells, rural/urban distribution networks, and irrigation pipelines.',
    keywords: ['upvc pipes', 'pvc pipes', 'drinking water pipes', 'plumbing pipes', 'water supply pipes', 'tubewell pipe', 'pressure pipe'],
    testingStandards: ['IS 12235'],
    clauseSnippet: 'Unplasticized PVC (uPVC) pipes for water supply shall strictly conform to IS 4985:2000 with mandatory BIS certification mark.'
  },
  {
    id: 'STD031',
    code: 'IS 3025 (Part 1):1987',
    cleanCode: 'IS 3025',
    title: 'Methods of Sampling and Test (Physical and Chemical) for Water and Wastewater',
    category: 'Water & Environment - Testing',
    year: 1987,
    mandatory: false,
    qcoStatus: 'Standard Testing Methodology',
    scope: 'Procedures for sample collection, storage, and standard analytical chemical testing of drinking water, groundwater, industrial effluent, and wastewater.',
    keywords: ['water testing', 'effluent testing', 'water sampling', 'bod cod', 'ph test', 'wastewater analysis', 'stp water test'],
    testingStandards: ['IS 3025'],
    clauseSnippet: 'Water testing and quality verification shall follow the standard procedures specified in IS 3025.'
  },
  {
    id: 'STD032',
    code: 'IS 15450:2004',
    cleanCode: 'IS 15450',
    title: 'Chlorinated Polyvinyl Chloride (CPVC) Pipes for Potable Hot and Cold Water',
    category: 'Water & Environment - Pipes',
    year: 2004,
    mandatory: false,
    qcoStatus: 'Standard Specification for High Temperature Plumbing',
    scope: 'CPVC pipes for domestic, commercial, and industrial internal plumbing distribution for both hot and cold potable water up to 93°C.',
    keywords: ['cpvc pipes', 'hot water pipes', 'chlorinated pvc', 'internal plumbing', 'water supply plumbing'],
    testingStandards: ['IS 15450'],
    clauseSnippet: 'Hot and cold water internal plumbing pipes shall conform to IS 15450:2004.'
  },

  // ── Safety & PPE ───────────────────────────────────────────────────────────
  {
    id: 'STD033',
    code: 'IS 2925:1984',
    cleanCode: 'IS 2925',
    title: 'Specification for Industrial Safety Helmets',
    category: 'Safety & PPE',
    year: 1984,
    mandatory: false,
    qcoStatus: 'National Safety Benchmark for PPE (Mandatory in DGMS/BOCW norms)',
    scope: 'Impact resistance, penetration resistance, flammability, and electrical insulation requirements for hard hats and industrial safety helmets.',
    keywords: ['safety helmets', 'hard hats', 'head protection', 'industrial helmet', 'construction helmet', 'ppe helmet', 'worker safety'],
    testingStandards: ['IS 2925'],
    clauseSnippet: 'Industrial safety helmets shall conform to IS 2925:1984 with adjustable ratchet harness and ISI marking.'
  },
  {
    id: 'STD034',
    code: 'IS 15298 (Part 2):2016',
    cleanCode: 'IS 15298 (Part 2)',
    title: 'Personal Eye-Protection — Specification',
    category: 'Safety & PPE',
    year: 2016,
    mandatory: false,
    qcoStatus: 'Standard Specification for Eye Safety',
    scope: 'Safety spectacles, goggles, face shields, and welding filters for protection against flying debris, chemical splash, molten metal, and UV/IR radiation.',
    keywords: ['safety goggles', 'eye protection', 'safety glasses', 'welding shield', 'face shield', 'worker eyewear'],
    testingStandards: ['IS 15298'],
    clauseSnippet: 'Eye protection gear and safety goggles shall conform to IS 15298 (Part 2):2016.'
  },
  {
    id: 'STD035',
    code: 'IS 15298 (Part 3):2016',
    cleanCode: 'IS 15298 (Part 3)',
    title: 'Personal Eye and Face Protection — Hand/Arm Protection',
    category: 'Safety & PPE',
    year: 2016,
    mandatory: false,
    qcoStatus: 'Standard Specification for Industrial Gloves',
    scope: 'Industrial protective gloves and arm guards protecting against mechanical hazards (abrasion, cut, tear, puncture) and chemical handling.',
    keywords: ['safety gloves', 'protective gloves', 'hand gloves', 'cut resistant gloves', 'industrial gloves', 'arm protection'],
    testingStandards: ['IS 15298'],
    clauseSnippet: 'Industrial protective gloves shall conform to IS 15298 (Part 3):2016.'
  },
  {
    id: 'STD036',
    code: 'IS 4770:1991',
    cleanCode: 'IS 4770',
    title: 'Rubber Gloves for Electrical Purposes — Specification',
    category: 'Safety & PPE',
    year: 1991,
    mandatory: true,
    qcoStatus: 'Mandatory under Electrical Safety Equipment QCO',
    scope: 'Dielectric insulating rubber gloves for line workers handling energized electrical equipment and live high-voltage power lines.',
    keywords: ['rubber gloves', 'electrical gloves', 'insulating gloves', 'high voltage gloves', 'lineman gloves', 'dielectric gloves'],
    testingStandards: ['IS 4770'],
    clauseSnippet: 'Electrical insulating rubber gloves shall strictly conform to IS 4770:1991 Class 1/2/3/4 with mandatory BIS certification mark.'
  },
  {
    id: 'STD037',
    code: 'IS 5983:2018',
    cleanCode: 'IS 5983',
    title: 'Respiratory Protective Devices — Eye and Face Protectors for Welding',
    category: 'Safety & PPE',
    year: 2018,
    mandatory: false,
    qcoStatus: 'Standard Specification for Industrial Welding & Respiratory Safety',
    scope: 'Industrial particulate respirators, chemical gas masks, dust masks, and welding protective screens for hazardous atmospheric work.',
    keywords: ['respirator', 'dust mask', 'gas mask', 'n95 mask', 'respiratory protection', 'air purifying respirator', 'breathing mask'],
    testingStandards: ['IS 5983'],
    clauseSnippet: 'Respiratory protective masks shall satisfy the filtration and breathing resistance parameters of IS 5983:2018.'
  },
  {
    id: 'STD038',
    code: 'IS 11226:1993',
    cleanCode: 'IS 11226',
    title: 'Leather Safety Footwear — Specification',
    category: 'Safety & PPE',
    year: 1993,
    mandatory: false,
    qcoStatus: 'Mandatory under Footwear Quality Control Order (QCO)',
    scope: 'Steel toe cap leather safety shoes and boots providing protection against heavy falling objects, compression, sole puncture, and oil/acid hazards.',
    keywords: ['safety shoes', 'safety footwear', 'steel toe boots', 'leather safety shoes', 'industrial boots', 'worker boots'],
    testingStandards: ['IS 11226'],
    clauseSnippet: 'Leather safety shoes with steel toe cap shall conform to IS 11226:1993 with BIS certification.'
  },

  // ── IT, Electronics & Security ─────────────────────────────────────────────
  {
    id: 'STD039',
    code: 'IS/ISO/IEC 27001:2013',
    cleanCode: 'IS/ISO/IEC 27001',
    title: 'Information Security Management Systems (ISMS) — Requirements',
    category: 'IT & Information Security',
    year: 2013,
    mandatory: false,
    qcoStatus: 'Mandatory in National Cyber Security & GeM Cloud Tenders',
    scope: 'International information security management framework adopted by BIS for evaluating IT systems, cloud providers, software development vendors, and data centers.',
    keywords: ['iso 27001', 'isms', 'information security', 'cybersecurity', 'cloud security', 'data protection', 'it procurement', 'software vendor certification'],
    testingStandards: ['ISO/IEC 27002'],
    clauseSnippet: 'IT service providers and software vendors must maintain certified compliance with IS/ISO/IEC 27001:2013.'
  },
  {
    id: 'STD040',
    code: 'IS 13252 (Part 1):2010',
    cleanCode: 'IS 13252',
    title: 'Information Technology Equipment — Safety — General Requirements',
    category: 'IT & Electronics',
    year: 2010,
    mandatory: true,
    qcoStatus: 'Mandatory under MeitY Compulsory Registration Scheme (CRS)',
    scope: 'Electrical and operational safety for IT and office hardware: desktop computers, servers, laptops, printers, scanners, monitors, and power supplies.',
    keywords: ['desktop computers', 'printers', 'servers', 'laptops', 'it hardware', 'office computers', 'computer monitors', 'scanners', 'electronic hardware', 'crs'],
    testingStandards: ['IS 13252'],
    clauseSnippet: 'All supplied IT hardware (desktops, laptops, printers) must possess valid BIS Compulsory Registration Scheme (CRS) certification under IS 13252 (Part 1):2010.'
  },

  // ── Furniture & Fixtures ───────────────────────────────────────────────────
  {
    id: 'STD041',
    code: 'IS 616:1990',
    cleanCode: 'IS 616',
    title: 'Application Guide for Bright Rolled Steel Furniture Strip',
    category: 'Furniture & Fixtures',
    year: 1990,
    mandatory: false,
    qcoStatus: 'Standard Specification for Office Furniture Fabrication',
    scope: 'Cold rolled steel strip material used in manufacture of office cupboards, steel desks, filing cabinets, and metallic furniture frames.',
    keywords: ['steel furniture', 'office furniture', 'steel cupboards', 'filing cabinet', 'furniture strip', 'almirah', 'office desks'],
    testingStandards: ['IS 616'],
    clauseSnippet: 'Steel strips used in fabrication of modular office furniture shall conform to IS 616:1990.'
  }
];

export const PROCUREMENT_EXAMPLES_BY_CATEGORY = {
  'Civil & Structural': [
    'Supply of TMT reinforcement bars Fe 500D grade for RCC column and beam work',
    'Procurement of 43 Grade Ordinary Portland Cement for RCC construction work',
    'Supply of hot-rolled structural steel I-beams and channels for warehouse shed fabrication',
    'Interlocking precast concrete paver blocks 80mm thickness for heavy vehicle parking lot',
    'Supply of precast solid concrete masonry blocks for partition walls'
  ],
  'Electrical & Power': [
    'PVC insulated copper conductor 1100V grade FRLS cables for office wiring',
    'Installation of pipe and plate earthing system for computer server room',
    'Heavy duty armoured 4-core aluminium power cable for underground substation feeder',
    'Low voltage MCCB and distribution switchgear panel for commercial building',
    'Energy-efficient 3-phase induction motor for water booster pumping station'
  ],
  'Water & Sanitation': [
    'Supply of uPVC pipes 110mm diameter Class 3 for drinking water distribution',
    'CPVC piping and brass fittings for hot and cold potable water plumbing',
    'Large diameter welded steel pipes 500mm OD for municipal raw water pipeline',
    'Comprehensive chemical and bacteriological drinking water testing as per Jal Jeevan Mission'
  ],
  'IT & Digital Infrastructure': [
    'Procurement of 100 desktop computers, LED monitors, and multifunction laser printers',
    'Selection of managed cloud hosting vendor with certified Information Security Management',
    'Rack-mounted enterprise servers and online UPS power backup units for data center'
  ],
  'Safety & Occupational PPE': [
    'Industrial safety helmets with ratchet harness and chin strap for construction workers',
    'Rubber insulating electrical gloves Class 2 for 11kV substation maintenance crew',
    'Leather safety footwear with steel toe cap for workshop and foundry workers',
    'Safety goggles and face shields for metal grinding and gas welding operations'
  ]
};
